// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
} from "@hey-api/client-axios";
import type {
  AuthJwtLoginData,
  AuthJwtLoginError,
  AuthJwtLoginResponse,
  AuthJwtLogoutError,
  AuthJwtLogoutResponse,
  RegisterRegisterData,
  RegisterRegisterError,
  RegisterRegisterResponse,
  ResetForgotPasswordData,
  ResetForgotPasswordError,
  ResetForgotPasswordResponse,
  ResetResetPasswordData,
  ResetResetPasswordError,
  ResetResetPasswordResponse,
  VerifyRequestTokenData,
  VerifyRequestTokenError,
  VerifyRequestTokenResponse,
  VerifyVerifyData,
  VerifyVerifyError,
  VerifyVerifyResponse,
  UsersCurrentUserError,
  UsersCurrentUserResponse,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserError,
  UsersPatchCurrentUserResponse,
  UsersUserData,
  UsersUserError,
  UsersUserResponse,
  UsersPatchUserData,
  UsersPatchUserError,
  UsersPatchUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserError,
  UsersDeleteUserResponse,
  ReadItemData,
  ReadItemError,
  ReadItemResponse,
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  UpdateItemData,
  UpdateItemError,
  UpdateItemResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  CreateSaleData,
  CreateSaleError,
  CreateSaleResponse,
  ListSalesData,
  ListSalesError,
  ListSalesResponse,
  ListDiscountRulesData,
  ListDiscountRulesError,
  ListDiscountRulesResponse,
  CreateDiscountRuleData,
  CreateDiscountRuleError,
  CreateDiscountRuleResponse,
  UpdateDiscountRuleData,
  UpdateDiscountRuleError,
  UpdateDiscountRuleResponse,
  DeleteDiscountRuleData,
  DeleteDiscountRuleError,
  DeleteDiscountRuleResponse,
  GetSaleData,
  GetSaleError,
  GetSaleResponse,
  CancelSaleData,
  CancelSaleError,
  CancelSaleResponse,
  AnalyticsSummaryData,
  AnalyticsSummaryError,
  AnalyticsSummaryResponse,
  AnalyticsByCategoryData,
  AnalyticsByCategoryError,
  AnalyticsByCategoryResponse,
  AnalyticsByPaymentMethodData,
  AnalyticsByPaymentMethodError,
  AnalyticsByPaymentMethodResponse,
  AnalyticsTopProductsData,
  AnalyticsTopProductsError,
  AnalyticsTopProductsResponse,
  AnalyticsCustomerInsightsData,
  AnalyticsCustomerInsightsError,
  AnalyticsCustomerInsightsResponse,
  AnalyticsProfitabilityData,
  AnalyticsProfitabilityError,
  AnalyticsProfitabilityResponse,
  AnalyticsRevenueTrendData,
  AnalyticsRevenueTrendError,
  AnalyticsRevenueTrendResponse,
  AnalyticsDayOfWeekData,
  AnalyticsDayOfWeekError,
  AnalyticsDayOfWeekResponse,
  AnalyticsPurchasesData,
  AnalyticsPurchasesError,
  AnalyticsPurchasesResponse,
  AnalyticsInventoryError,
  AnalyticsInventoryResponse,
  AnalyticsDiscountsData,
  AnalyticsDiscountsError,
  AnalyticsDiscountsResponse,
  AnalyticsCustomersAdvancedData,
  AnalyticsCustomersAdvancedError,
  AnalyticsCustomersAdvancedResponse,
  AnalyticsCancellationsData,
  AnalyticsCancellationsError,
  AnalyticsCancellationsResponse,
  AnalyticsCashboxData,
  AnalyticsCashboxError,
  AnalyticsCashboxResponse,
  AnalyticsPeakTimesData,
  AnalyticsPeakTimesError,
  AnalyticsPeakTimesResponse,
  AnalyticsBasketData,
  AnalyticsBasketError,
  AnalyticsBasketResponse,
  CreatePurchaseData,
  CreatePurchaseError,
  CreatePurchaseResponse,
  ListPurchasesData,
  ListPurchasesError,
  ListPurchasesResponse,
  GetPurchaseData,
  GetPurchaseError,
  GetPurchaseResponse,
  ListCustomersData,
  ListCustomersError,
  ListCustomersResponse,
  CreateCustomerData,
  CreateCustomerError,
  CreateCustomerResponse,
  GetCustomerData,
  GetCustomerError,
  GetCustomerResponse,
  UpdateCustomerData,
  UpdateCustomerError,
  UpdateCustomerResponse,
  RecordPaymentData,
  RecordPaymentError,
  RecordPaymentResponse,
  RecordOutcomeData,
  RecordOutcomeError,
  RecordOutcomeResponse,
  DeletePaymentData,
  DeletePaymentError,
  DeletePaymentResponse,
  DeleteOutcomeData,
  DeleteOutcomeError,
  DeleteOutcomeResponse,
  GetCurrentSessionError,
  GetCurrentSessionResponse,
  OpenSessionData,
  OpenSessionError,
  OpenSessionResponse,
  CloseSessionData,
  CloseSessionError,
  CloseSessionResponse,
  AddManualTransactionData,
  AddManualTransactionError,
  AddManualTransactionResponse,
  ListTransactionsData,
  ListTransactionsError,
  ListTransactionsResponse,
  ListSessionsData,
  ListSessionsError,
  ListSessionsResponse,
  GetSessionData,
  GetSessionError,
  GetSessionResponse,
  SearchCategoriesData,
  SearchCategoriesError,
  SearchCategoriesResponse,
  SearchSuppliersData,
  SearchSuppliersError,
  SearchSuppliersResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLoginResponse,
    AuthJwtLoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/jwt/login",
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponse,
    AuthJwtLogoutError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/jwt/logout",
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RegisterRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterRegisterResponse,
    RegisterRegisterError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/register",
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetForgotPasswordResponse,
    ResetForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/forgot-password",
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetResetPasswordResponse,
    ResetResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/reset-password",
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyRequestTokenResponse,
    VerifyRequestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/request-verify-token",
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyVerifyResponse,
    VerifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/verify",
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponse,
    UsersCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchCurrentUserResponse,
    UsersPatchCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUserResponse,
    UsersUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchUserResponse,
    UsersPatchUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserResponse,
    UsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponse,
    ReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateItemResponse,
    CreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Update Item
 */
export const updateItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateItemResponse,
    UpdateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteItemResponse,
    DeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Create Sale
 */
export const createSale = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateSaleData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateSaleResponse,
    CreateSaleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/",
  });
};

/**
 * List Sales
 */
export const listSales = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListSalesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSalesResponse,
    ListSalesError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/",
  });
};

/**
 * List Discount Rules
 */
export const listDiscountRules = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListDiscountRulesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListDiscountRulesResponse,
    ListDiscountRulesError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/discount-rules",
  });
};

/**
 * Create Discount Rule
 */
export const createDiscountRule = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateDiscountRuleData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateDiscountRuleResponse,
    CreateDiscountRuleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/discount-rules",
  });
};

/**
 * Update Discount Rule
 */
export const updateDiscountRule = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateDiscountRuleData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateDiscountRuleResponse,
    UpdateDiscountRuleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/discount-rules/{rule_id}",
  });
};

/**
 * Delete Discount Rule
 */
export const deleteDiscountRule = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteDiscountRuleData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteDiscountRuleResponse,
    DeleteDiscountRuleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/discount-rules/{rule_id}",
  });
};

/**
 * Get Sale
 */
export const getSale = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetSaleData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSaleResponse,
    GetSaleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/{sale_id}",
  });
};

/**
 * Cancel Sale
 */
export const cancelSale = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CancelSaleData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CancelSaleResponse,
    CancelSaleError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/{sale_id}/cancel",
  });
};

/**
 * Analytics Summary
 */
export const analyticsSummary = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsSummaryResponse,
    AnalyticsSummaryError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/summary",
  });
};

/**
 * Analytics By Category
 */
export const analyticsByCategory = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsByCategoryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsByCategoryResponse,
    AnalyticsByCategoryError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/by-category",
  });
};

/**
 * Analytics By Payment Method
 */
export const analyticsByPaymentMethod = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsByPaymentMethodData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsByPaymentMethodResponse,
    AnalyticsByPaymentMethodError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/by-payment-method",
  });
};

/**
 * Analytics Top Products
 */
export const analyticsTopProducts = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsTopProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsTopProductsResponse,
    AnalyticsTopProductsError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/top-products",
  });
};

/**
 * Analytics Customer Insights
 */
export const analyticsCustomerInsights = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsCustomerInsightsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsCustomerInsightsResponse,
    AnalyticsCustomerInsightsError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/customer-insights",
  });
};

/**
 * Analytics Profitability
 */
export const analyticsProfitability = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsProfitabilityData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsProfitabilityResponse,
    AnalyticsProfitabilityError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/profitability",
  });
};

/**
 * Analytics Revenue Trend
 */
export const analyticsRevenueTrend = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsRevenueTrendData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsRevenueTrendResponse,
    AnalyticsRevenueTrendError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/revenue-trend",
  });
};

/**
 * Analytics Day Of Week
 */
export const analyticsDayOfWeek = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsDayOfWeekData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsDayOfWeekResponse,
    AnalyticsDayOfWeekError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/day-of-week",
  });
};

/**
 * Analytics Purchases
 */
export const analyticsPurchases = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsPurchasesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsPurchasesResponse,
    AnalyticsPurchasesError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/purchases",
  });
};

/**
 * Analytics Inventory
 */
export const analyticsInventory = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsInventoryResponse,
    AnalyticsInventoryError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/inventory",
  });
};

/**
 * Analytics Discounts
 */
export const analyticsDiscounts = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsDiscountsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsDiscountsResponse,
    AnalyticsDiscountsError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/discounts",
  });
};

/**
 * Analytics Customers Advanced
 */
export const analyticsCustomersAdvanced = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<AnalyticsCustomersAdvancedData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsCustomersAdvancedResponse,
    AnalyticsCustomersAdvancedError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/customers-advanced",
  });
};

/**
 * Analytics Cancellations
 */
export const analyticsCancellations = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsCancellationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsCancellationsResponse,
    AnalyticsCancellationsError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/cancellations",
  });
};

/**
 * Analytics Cashbox
 */
export const analyticsCashbox = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsCashboxData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsCashboxResponse,
    AnalyticsCashboxError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/cashbox",
  });
};

/**
 * Analytics Peak Times
 */
export const analyticsPeakTimes = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsPeakTimesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsPeakTimesResponse,
    AnalyticsPeakTimesError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/peak-times",
  });
};

/**
 * Analytics Basket
 */
export const analyticsBasket = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AnalyticsBasketData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnalyticsBasketResponse,
    AnalyticsBasketError,
    ThrowOnError
  >({
    ...options,
    url: "/sales/analytics/basket",
  });
};

/**
 * Create Purchase
 */
export const createPurchase = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreatePurchaseData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreatePurchaseResponse,
    CreatePurchaseError,
    ThrowOnError
  >({
    ...options,
    url: "/purchases/",
  });
};

/**
 * List Purchases
 */
export const listPurchases = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListPurchasesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListPurchasesResponse,
    ListPurchasesError,
    ThrowOnError
  >({
    ...options,
    url: "/purchases/",
  });
};

/**
 * Get Purchase
 */
export const getPurchase = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetPurchaseData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPurchaseResponse,
    GetPurchaseError,
    ThrowOnError
  >({
    ...options,
    url: "/purchases/{purchase_id}",
  });
};

/**
 * List Customers
 */
export const listCustomers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListCustomersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListCustomersResponse,
    ListCustomersError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/",
  });
};

/**
 * Create Customer
 */
export const createCustomer = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateCustomerData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateCustomerResponse,
    CreateCustomerError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/",
  });
};

/**
 * Get Customer
 */
export const getCustomer = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetCustomerData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCustomerResponse,
    GetCustomerError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}",
  });
};

/**
 * Update Customer
 */
export const updateCustomer = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateCustomerData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateCustomerResponse,
    UpdateCustomerError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}",
  });
};

/**
 * Record Payment
 */
export const recordPayment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RecordPaymentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RecordPaymentResponse,
    RecordPaymentError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}/payments",
  });
};

/**
 * Record Outcome
 */
export const recordOutcome = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RecordOutcomeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RecordOutcomeResponse,
    RecordOutcomeError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}/outcomes",
  });
};

/**
 * Delete Payment
 */
export const deletePayment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeletePaymentData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeletePaymentResponse,
    DeletePaymentError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}/payments/{payment_id}",
  });
};

/**
 * Delete Outcome
 */
export const deleteOutcome = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteOutcomeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteOutcomeResponse,
    DeleteOutcomeError,
    ThrowOnError
  >({
    ...options,
    url: "/customers/{customer_id}/outcomes/{outcome_id}",
  });
};

/**
 * Get Current Session
 */
export const getCurrentSession = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentSessionResponse,
    GetCurrentSessionError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/session/current",
  });
};

/**
 * Open Session
 */
export const openSession = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OpenSessionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OpenSessionResponse,
    OpenSessionError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/session/open",
  });
};

/**
 * Close Session
 */
export const closeSession = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CloseSessionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CloseSessionResponse,
    CloseSessionError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/session/close",
  });
};

/**
 * Add Manual Transaction
 */
export const addManualTransaction = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AddManualTransactionData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AddManualTransactionResponse,
    AddManualTransactionError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/transactions",
  });
};

/**
 * List Transactions
 */
export const listTransactions = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListTransactionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListTransactionsResponse,
    ListTransactionsError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/transactions",
  });
};

/**
 * List Sessions
 */
export const listSessions = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListSessionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSessionsResponse,
    ListSessionsError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/sessions",
  });
};

/**
 * Get Session
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetSessionData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSessionResponse,
    GetSessionError,
    ThrowOnError
  >({
    ...options,
    url: "/cashbox/sessions/{session_id}",
  });
};

/**
 * Search Categories
 */
export const searchCategories = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<SearchCategoriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchCategoriesResponse,
    SearchCategoriesError,
    ThrowOnError
  >({
    ...options,
    url: "/categories/",
  });
};

/**
 * Search Suppliers
 */
export const searchSuppliers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<SearchSuppliersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchSuppliersResponse,
    SearchSuppliersError,
    ThrowOnError
  >({
    ...options,
    url: "/suppliers/",
  });
};
