// This file is auto-generated by @hey-api/openapi-ts

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_type?: UnitType;
  stock?: number | string;
  min_stock?: number | string | null;
  price?: number | string | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_type?: UnitType;
  stock?: string;
  min_stock?: string | null;
  price?: string | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Page_ItemRead_ = {
  items: Array<ItemRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_PurchaseRead_ = {
  items: Array<PurchaseRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_SaleRead_ = {
  items: Array<SaleRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type PaymentMethod = "cash" | "card" | "other";

export type PurchaseCreate = {
  supplier_name?: string | null;
  reference_number?: string | null;
  purchase_date?: string | null;
  payment_method?: PurchasePaymentMethod;
  payment_status?: PurchasePaymentStatus;
  tax?: number | string;
  notes?: string | null;
  items: Array<PurchaseItemCreate>;
};

export type PurchaseItemCreate = {
  item_id?: string | null;
  item_name: string;
  unit_type?: string;
  quantity: number | string;
  cost_price: number | string;
  sku?: string | null;
  category?: string | null;
};

export type PurchaseItemRead = {
  id: string;
  item_id: string | null;
  item_name: string;
  unit_type: string;
  quantity: string;
  cost_price: string;
  subtotal: string;
};

export type PurchasePaymentMethod = "cash" | "card" | "transfer" | "credit";

export type PurchasePaymentStatus = "paid" | "unpaid" | "partial";

export type PurchaseRead = {
  id: string;
  supplier_name: string | null;
  reference_number: string | null;
  purchase_date: string;
  created_at: string;
  status: PurchaseStatus;
  payment_status: PurchasePaymentStatus;
  payment_method: PurchasePaymentMethod;
  subtotal: string;
  tax: string;
  total_cost: string;
  notes: string | null;
  purchase_items: Array<PurchaseItemRead>;
};

export type PurchaseStatus = "received" | "partial" | "cancelled";

export type SaleCreate = {
  items: Array<SaleItemCreate>;
  payment_method?: PaymentMethod;
  amount_tendered?: number | string | null;
  notes?: string | null;
};

export type SaleItemCreate = {
  item_id: string;
  quantity: number | string;
};

export type SaleItemRead = {
  id: string;
  item_id: string | null;
  item_name: string;
  unit_type: string;
  unit_price: string;
  quantity: string;
  subtotal: string;
};

export type SaleRead = {
  id: string;
  created_at: string;
  total: string;
  status: SaleStatus;
  payment_method: PaymentMethod;
  amount_tendered: string | null;
  change_given: string | null;
  notes: string | null;
  sale_items: Array<SaleItemRead>;
};

export type SaleStatus = "completed" | "cancelled" | "refunded";

export type UnitType = "unit" | "kg" | "gram" | "liter" | "pack";

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  username?: string | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  username?: string | null;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  username?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type ReadItemData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Search query (name, SKU, or category)
     */
    q?: string | null;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadItemResponse = Page_ItemRead_;

export type ReadItemError = HTTPValidationError;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type CreateSaleData = {
  body: SaleCreate;
};

export type CreateSaleResponse = SaleRead;

export type CreateSaleError = HTTPValidationError;

export type ListSalesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ListSalesResponse = Page_SaleRead_;

export type ListSalesError = HTTPValidationError;

export type GetSaleData = {
  path: {
    sale_id: string;
  };
};

export type GetSaleResponse = SaleRead;

export type GetSaleError = HTTPValidationError;

export type CreatePurchaseData = {
  body: PurchaseCreate;
};

export type CreatePurchaseResponse = PurchaseRead;

export type CreatePurchaseError = HTTPValidationError;

export type ListPurchasesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ListPurchasesResponse = Page_PurchaseRead_;

export type ListPurchasesError = HTTPValidationError;

export type GetPurchaseData = {
  path: {
    purchase_id: string;
  };
};

export type GetPurchaseResponse = PurchaseRead;

export type GetPurchaseError = HTTPValidationError;
