// This file is auto-generated by @hey-api/openapi-ts

export type AdvancedCustomerSchema = {
  customerId: string;
  name: string;
  totalSpent: number;
  orderCount: number;
  creditOwed: number;
};

export type AnalyticsSummarySchema = {
  totalRevenue: number;
  totalOrders: number;
  avgOrderValue: number;
  topCategory: TopCategorySchema | null;
};

export type BasketAnalysisSchema = {
  topPairs: Array<CategoryPairSchema>;
  totalBaskets: number;
  avgItemsPerBasket: number;
};

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type CancellationAnalyticsSchema = {
  cancelledCount: number;
  cancelledRevenue: number;
  refundedCount: number;
  refundedRevenue: number;
  totalLostRevenue: number;
  refundRate: number;
};

export type CashboxAnalyticsSchema = {
  totalInflow: number;
  totalOutflow: number;
  netCashflow: number;
  byType: Array<CashboxTypeStatSchema>;
};

export type CashboxManualTransaction = {
  type: string;
  amount: number | string;
  payment_method?: string;
  description?: string | null;
};

export type CashboxSessionClose = {
  closing_amount_counted: number | string;
  notes?: string | null;
};

export type CashboxSessionCreate = {
  opening_amount?: number | string;
  notes?: string | null;
};

export type CashboxSessionList = {
  items: Array<CashboxSessionRead>;
  total: number;
  page: number;
  size: number;
  pages: number;
};

export type CashboxSessionRead = {
  id: string;
  opening_amount: string;
  status: string;
  opened_at: string;
  closed_at: string | null;
  closing_amount_counted: string | null;
  notes: string | null;
  created_at: string;
  cash_in?: string;
  cash_out?: string;
  card_in?: string;
  transfer_in?: string;
  credit_sales?: string;
  owner_withdrawals?: string;
  expected_cash_balance?: string;
  difference?: string | null;
  transaction_count?: number;
};

export type CashboxTransactionRead = {
  id: string;
  session_id: string | null;
  type: string;
  direction: string;
  amount: string;
  payment_method: string;
  reference_type: string | null;
  reference_id: string | null;
  description: string | null;
  created_at: string;
};

export type CashboxTypeStatSchema = {
  type: string;
  direction: string;
  amount: number;
  count: number;
};

export type CategoryPairSchema = {
  categoryA: string;
  categoryB: string;
  count: number;
  percentage: number;
  totalRevenue: number;
};

export type CategoryStatSchema = {
  category: string;
  revenue: number;
  quantity: number;
  orderCount: number;
};

export type CustomerCreate = {
  name: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  id_number?: string | null;
  credit_limit?: number | string | null;
  notes?: string | null;
};

export type CustomerDetailRead = {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  id_number: string | null;
  credit_limit: string | null;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  total_credit?: string;
  total_outcomes?: string;
  total_paid?: string;
  balance?: string;
  credit_sales?: Array<SaleRead>;
  payments?: Array<CustomerPaymentRead>;
  outcomes?: Array<CustomerOutcomeRead>;
};

export type CustomerInsightSchema = {
  customerId: string;
  name: string;
  totalSpent: number;
  orderCount: number;
  avgOrder: number;
  lastOrder: string;
};

export type CustomerOutcomeCreate = {
  amount: number | string;
  description: string;
  outcome_date?: string | null;
};

export type CustomerOutcomeRead = {
  id: string;
  amount: string;
  description: string;
  outcome_date: string;
  created_at: string;
};

export type CustomerPage = {
  items: Array<CustomerRead>;
  total: number;
  page: number;
  size: number;
  pages: number;
};

export type CustomerPaymentCreate = {
  amount: number | string;
  payment_method?: string;
  payment_date?: string | null;
  notes?: string | null;
};

export type CustomerPaymentRead = {
  id: string;
  amount: string;
  payment_method: string;
  payment_date: string;
  notes: string | null;
  created_at: string;
};

export type CustomerRead = {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  id_number: string | null;
  credit_limit: string | null;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  total_credit?: string;
  total_outcomes?: string;
  total_paid?: string;
  balance?: string;
};

export type CustomersAdvancedSchema = {
  totalCustomers: number;
  activeCustomers: number;
  repeatCustomers: number;
  repeatRate: number;
  creditOutstanding: number;
  topByValue: Array<AdvancedCustomerSchema>;
};

export type CustomerUpdate = {
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  id_number?: string | null;
  credit_limit?: number | string | null;
  notes?: string | null;
  is_active?: boolean | null;
};

export type DayOfWeekSchema = {
  day: string;
  revenue: number;
  orders: number;
  avgOrderValue: number;
};

export type DeadStockItemSchema = {
  itemId: string;
  name: string;
  stock: number;
  category: string;
  lastSold: string | null;
};

export type DiscountAnalyticsSchema = {
  totalDiscountAmount: number;
  discountedSaleCount: number;
  totalSalesCount: number;
  discountRate: number;
  byRule: Array<DiscountRuleStatSchema>;
};

export type DiscountRuleScope = "global" | "item" | "category";

export type DiscountRuleStatSchema = {
  ruleName: string;
  usageCount: number;
  totalDiscount: number;
};

export type DiscountRuleType = "percent" | "fixed_price" | "buy_x_get_y";

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type InventoryAnalyticsSchema = {
  totalInventoryValue: number;
  totalItems: number;
  lowStockItems: Array<LowStockItemSchema>;
  deadStockItems: Array<DeadStockItemSchema>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_type?: UnitType;
  stock?: number | string;
  min_stock?: number | string | null;
  price?: number | string | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_type?: UnitType;
  stock?: string;
  min_stock?: string | null;
  price?: string | null;
  id: string;
  user_id: string;
  is_deleted?: boolean;
};

export type ItemUpdate = {
  name?: string | null;
  description?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_type?: UnitType | null;
  stock?: number | string | null;
  min_stock?: number | string | null;
  price?: number | string | null;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type LowStockItemSchema = {
  itemId: string;
  name: string;
  stock: number;
  minStock: number | null;
  category: string;
  unitType: string;
};

export type Page_ItemRead_ = {
  items: Array<ItemRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_PurchaseRead_ = {
  items: Array<PurchaseRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_SaleRead_ = {
  items: Array<SaleRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type PaymentMethod = "cash" | "card" | "other" | "credit" | "internal";

export type PaymentMethodStatSchema = {
  method: string;
  revenue: number;
  count: number;
  percentage: number;
};

export type PeakTimesSchema = {
  byTimeBlock: Array<TimeBlockStatSchema>;
  byDayOfWeek: Array<{
    [key: string]: unknown;
  }>;
};

export type ProfitabilitySchema = {
  totalRevenue: number;
  totalCOGS: number;
  grossProfit: number;
  grossMarginPercent: number;
  topProfitableProducts: Array<ProfitableProductSchema>;
  leastProfitableProducts: Array<ProfitableProductSchema>;
};

export type ProfitableProductSchema = {
  itemId: string;
  name: string;
  category: string;
  revenue: number;
  cost: number;
  profit: number;
  margin: number;
  quantity: number;
};

export type PurchaseAnalyticsSchema = {
  totalSpend: number;
  totalPurchases: number;
  avgPurchaseValue: number;
  bySupplier: Array<SupplierSpendSchema>;
  byPaymentStatus: Array<PurchasePaymentStatusSchema>;
};

export type PurchaseCreate = {
  supplier?: SupplierCreate | null;
  reference_number?: string | null;
  purchase_date?: string | null;
  payment_method?: PurchasePaymentMethod;
  payment_status?: PurchasePaymentStatus;
  tax?: number | string;
  notes?: string | null;
  items: Array<PurchaseItemCreate>;
};

export type PurchaseItemCreate = {
  item_id?: string | null;
  item_name: string;
  unit_type?: string;
  quantity: number | string;
  total_cost_price: number | string;
  sku?: string | null;
  category?: string | null;
  sell_price?: number | string | null;
  overwrite_previous_value?: boolean;
};

export type PurchaseItemRead = {
  id: string;
  item_id: string | null;
  item_name: string;
  unit_type: string;
  quantity: string;
  cost_price: string;
  subtotal: string;
};

export type PurchasePaymentMethod = "cash" | "card" | "transfer" | "credit";

export type PurchasePaymentStatus = "paid" | "unpaid" | "partial";

export type PurchasePaymentStatusSchema = {
  status: string;
  count: number;
  total: number;
};

export type PurchaseRead = {
  id: string;
  supplier: SupplierRead | null;
  reference_number: string | null;
  purchase_date: string;
  created_at: string;
  status: PurchaseStatus;
  payment_status: PurchasePaymentStatus;
  payment_method: PurchasePaymentMethod;
  subtotal: string;
  tax: string;
  total_cost: string;
  notes: string | null;
  purchase_items: Array<PurchaseItemRead>;
};

export type PurchaseStatus = "received" | "partial" | "cancelled";

export type QuantityDiscountRuleCreate = {
  name: string;
  scope?: DiscountRuleScope;
  item_id?: string | null;
  category?: string | null;
  is_active?: boolean;
  priority?: number | string;
  min_qty: number | string;
  rule_type: DiscountRuleType;
  percent_off?: number | string | null;
  fixed_unit_price?: number | string | null;
  buy_qty?: number | string | null;
  free_qty?: number | string | null;
};

export type QuantityDiscountRuleRead = {
  id: string;
  name: string;
  scope: string;
  item_id: string | null;
  category: string | null;
  is_active: boolean;
  priority: string;
  min_qty: string;
  rule_type: string;
  percent_off: string | null;
  fixed_unit_price: string | null;
  buy_qty: string | null;
  free_qty: string | null;
};

export type QuantityDiscountRuleUpdate = {
  name?: string | null;
  scope?: DiscountRuleScope | null;
  item_id?: string | null;
  category?: string | null;
  is_active?: boolean | null;
  priority?: number | string | null;
  min_qty?: number | string | null;
  rule_type?: DiscountRuleType | null;
  percent_off?: number | string | null;
  fixed_unit_price?: number | string | null;
  buy_qty?: number | string | null;
  free_qty?: number | string | null;
};

export type RevenueTrendSchema = {
  data: Array<TrendPointSchema>;
};

export type SaleCreate = {
  items: Array<SaleItemCreate>;
  payment_method?: PaymentMethod;
  amount_tendered?: number | string | null;
  notes?: string | null;
  customer_id?: string | null;
  subtotal_override?: number | string | null;
  subtotal_override_reason?: string | null;
};

export type SaleItemCreate = {
  item_id: string;
  quantity: number | string;
  unit_price_override?: number | string | null;
  manual_override_reason?: string | null;
};

export type SaleItemRead = {
  id: string;
  item_id: string | null;
  item_name: string;
  unit_type: string;
  base_unit_price: string;
  unit_price: string;
  quantity: string;
  subtotal: string;
  pricing_source?: string | null;
  discount_rule_name?: string | null;
  discount_amount?: string | null;
  manual_override_reason?: string | null;
};

export type SaleRead = {
  id: string;
  created_at: string;
  total: string;
  status: SaleStatus;
  payment_method: PaymentMethod;
  amount_tendered: string | null;
  change_given: string | null;
  notes: string | null;
  customer_id?: string | null;
  customer_name?: string | null;
  sale_items: Array<SaleItemRead>;
};

export type SaleStatus = "completed" | "cancelled" | "refunded";

export type SupplierCreate = {
  id?: string | null;
  name: string;
};

export type SupplierRead = {
  id: string;
  name: string;
};

export type SupplierSpendSchema = {
  supplierId: string;
  name: string;
  totalSpend: number;
  purchaseCount: number;
};

export type TimeBlockStatSchema = {
  block: string;
  label: string;
  revenue: number;
  orders: number;
  percentage: number;
};

export type TopCategorySchema = {
  name: string;
  revenue: number;
};

export type TopProductSchema = {
  itemId: string;
  name: string;
  revenue: number;
  quantity: number;
  orderCount: number;
  category: string;
};

export type TrendPointSchema = {
  period: string;
  revenue: number;
  orders: number;
  avgOrderValue: number;
};

export type UnitType = "unit" | "gram" | "liter" | "pack";

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  username?: string | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  username?: string | null;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  username?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type ReadItemData = {
  query?: {
    /**
     * Filter by exact category name
     */
    category?: string | null;
    /**
     * Order by field (e.g., 'name', '-price')
     */
    order?: string | null;
    /**
     * Page number
     */
    page?: number;
    /**
     * Search query (name, SKU, or category)
     */
    q?: string | null;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadItemResponse = Page_ItemRead_;

export type ReadItemError = HTTPValidationError;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type UpdateItemData = {
  body: ItemUpdate;
  path: {
    item_id: string;
  };
};

export type UpdateItemResponse = ItemRead;

export type UpdateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type CreateSaleData = {
  body: SaleCreate;
};

export type CreateSaleResponse = SaleRead;

export type CreateSaleError = HTTPValidationError;

export type ListSalesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    payment_method?: string | null;
    /**
     * Page size
     */
    size?: number;
    status?: string | null;
  };
};

export type ListSalesResponse = Page_SaleRead_;

export type ListSalesError = HTTPValidationError;

export type ListDiscountRulesData = {
  query?: {
    include_inactive?: boolean;
    item_id?: string | null;
  };
};

export type ListDiscountRulesResponse = Array<QuantityDiscountRuleRead>;

export type ListDiscountRulesError = HTTPValidationError;

export type CreateDiscountRuleData = {
  body: QuantityDiscountRuleCreate;
};

export type CreateDiscountRuleResponse = QuantityDiscountRuleRead;

export type CreateDiscountRuleError = HTTPValidationError;

export type UpdateDiscountRuleData = {
  body: QuantityDiscountRuleUpdate;
  path: {
    rule_id: string;
  };
};

export type UpdateDiscountRuleResponse = QuantityDiscountRuleRead;

export type UpdateDiscountRuleError = HTTPValidationError;

export type DeleteDiscountRuleData = {
  path: {
    rule_id: string;
  };
};

export type DeleteDiscountRuleResponse = void;

export type DeleteDiscountRuleError = HTTPValidationError;

export type GetSaleData = {
  path: {
    sale_id: string;
  };
};

export type GetSaleResponse = SaleRead;

export type GetSaleError = HTTPValidationError;

export type CancelSaleData = {
  path: {
    sale_id: string;
  };
};

export type CancelSaleResponse = SaleRead;

export type CancelSaleError = HTTPValidationError;

export type AnalyticsSummaryData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsSummaryResponse = AnalyticsSummarySchema;

export type AnalyticsSummaryError = HTTPValidationError;

export type AnalyticsByCategoryData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsByCategoryResponse = Array<CategoryStatSchema>;

export type AnalyticsByCategoryError = HTTPValidationError;

export type AnalyticsByPaymentMethodData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsByPaymentMethodResponse = Array<PaymentMethodStatSchema>;

export type AnalyticsByPaymentMethodError = HTTPValidationError;

export type AnalyticsTopProductsData = {
  query?: {
    end_date?: string | null;
    limit?: number;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsTopProductsResponse = Array<TopProductSchema>;

export type AnalyticsTopProductsError = HTTPValidationError;

export type AnalyticsCustomerInsightsData = {
  query?: {
    end_date?: string | null;
    limit?: number;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsCustomerInsightsResponse = Array<CustomerInsightSchema>;

export type AnalyticsCustomerInsightsError = HTTPValidationError;

export type AnalyticsProfitabilityData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsProfitabilityResponse = ProfitabilitySchema;

export type AnalyticsProfitabilityError = HTTPValidationError;

export type AnalyticsRevenueTrendData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsRevenueTrendResponse = RevenueTrendSchema;

export type AnalyticsRevenueTrendError = HTTPValidationError;

export type AnalyticsDayOfWeekData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsDayOfWeekResponse = Array<DayOfWeekSchema>;

export type AnalyticsDayOfWeekError = HTTPValidationError;

export type AnalyticsPurchasesData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsPurchasesResponse = PurchaseAnalyticsSchema;

export type AnalyticsPurchasesError = HTTPValidationError;

export type AnalyticsInventoryResponse = InventoryAnalyticsSchema;

export type AnalyticsInventoryError = unknown;

export type AnalyticsDiscountsData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsDiscountsResponse = DiscountAnalyticsSchema;

export type AnalyticsDiscountsError = HTTPValidationError;

export type AnalyticsCustomersAdvancedData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsCustomersAdvancedResponse = CustomersAdvancedSchema;

export type AnalyticsCustomersAdvancedError = HTTPValidationError;

export type AnalyticsCancellationsData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsCancellationsResponse = CancellationAnalyticsSchema;

export type AnalyticsCancellationsError = HTTPValidationError;

export type AnalyticsCashboxData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsCashboxResponse = CashboxAnalyticsSchema;

export type AnalyticsCashboxError = HTTPValidationError;

export type AnalyticsPeakTimesData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsPeakTimesResponse = PeakTimesSchema;

export type AnalyticsPeakTimesError = HTTPValidationError;

export type AnalyticsBasketData = {
  query?: {
    end_date?: string | null;
    period?: string;
    start_date?: string | null;
  };
};

export type AnalyticsBasketResponse = BasketAnalysisSchema;

export type AnalyticsBasketError = HTTPValidationError;

export type CreatePurchaseData = {
  body: PurchaseCreate;
};

export type CreatePurchaseResponse = PurchaseRead;

export type CreatePurchaseError = HTTPValidationError;

export type ListPurchasesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    payment_status?: string | null;
    q?: string | null;
    /**
     * Page size
     */
    size?: number;
    status?: string | null;
  };
};

export type ListPurchasesResponse = Page_PurchaseRead_;

export type ListPurchasesError = HTTPValidationError;

export type GetPurchaseData = {
  path: {
    purchase_id: string;
  };
};

export type GetPurchaseResponse = PurchaseRead;

export type GetPurchaseError = HTTPValidationError;

export type ListCustomersData = {
  query?: {
    page?: number;
    q?: string | null;
    show_inactive?: boolean;
    size?: number;
  };
};

export type ListCustomersResponse = CustomerPage;

export type ListCustomersError = HTTPValidationError;

export type CreateCustomerData = {
  body: CustomerCreate;
};

export type CreateCustomerResponse = CustomerRead;

export type CreateCustomerError = HTTPValidationError;

export type GetCustomerData = {
  path: {
    customer_id: string;
  };
};

export type GetCustomerResponse = CustomerDetailRead;

export type GetCustomerError = HTTPValidationError;

export type UpdateCustomerData = {
  body: CustomerUpdate;
  path: {
    customer_id: string;
  };
};

export type UpdateCustomerResponse = CustomerRead;

export type UpdateCustomerError = HTTPValidationError;

export type RecordPaymentData = {
  body: CustomerPaymentCreate;
  path: {
    customer_id: string;
  };
};

export type RecordPaymentResponse = CustomerPaymentRead;

export type RecordPaymentError = HTTPValidationError;

export type RecordOutcomeData = {
  body: CustomerOutcomeCreate;
  path: {
    customer_id: string;
  };
};

export type RecordOutcomeResponse = CustomerOutcomeRead;

export type RecordOutcomeError = HTTPValidationError;

export type DeletePaymentData = {
  path: {
    customer_id: string;
    payment_id: string;
  };
};

export type DeletePaymentResponse = unknown;

export type DeletePaymentError = HTTPValidationError;

export type DeleteOutcomeData = {
  path: {
    customer_id: string;
    outcome_id: string;
  };
};

export type DeleteOutcomeResponse = unknown;

export type DeleteOutcomeError = HTTPValidationError;

export type GetCurrentSessionResponse = CashboxSessionRead;

export type GetCurrentSessionError = unknown;

export type OpenSessionData = {
  body: CashboxSessionCreate;
};

export type OpenSessionResponse = CashboxSessionRead;

export type OpenSessionError = HTTPValidationError;

export type CloseSessionData = {
  body: CashboxSessionClose;
};

export type CloseSessionResponse = CashboxSessionRead;

export type CloseSessionError = HTTPValidationError;

export type AddManualTransactionData = {
  body: CashboxManualTransaction;
};

export type AddManualTransactionResponse = CashboxTransactionRead;

export type AddManualTransactionError = HTTPValidationError;

export type ListTransactionsData = {
  query?: {
    limit?: number;
    session_id?: string | null;
  };
};

export type ListTransactionsResponse = Array<CashboxTransactionRead>;

export type ListTransactionsError = HTTPValidationError;

export type ListSessionsData = {
  query?: {
    /**
     * all|today|yesterday|week|custom
     */
    filter?: string;
    /**
     * YYYY-MM-DD for custom filter
     */
    filter_date?: string | null;
    page?: number;
    size?: number;
  };
};

export type ListSessionsResponse = CashboxSessionList;

export type ListSessionsError = HTTPValidationError;

export type GetSessionData = {
  path: {
    session_id: string;
  };
};

export type GetSessionResponse = CashboxSessionRead;

export type GetSessionError = HTTPValidationError;

export type SearchCategoriesData = {
  query?: {
    limit?: number;
    /**
     * Search prefix
     */
    q?: string | null;
  };
};

export type SearchCategoriesResponse = Array<string>;

export type SearchCategoriesError = HTTPValidationError;

export type SearchSuppliersData = {
  query?: {
    limit?: number;
    /**
     * Search prefix
     */
    q?: string | null;
  };
};

export type SearchSuppliersResponse = Array<SupplierRead>;

export type SearchSuppliersError = HTTPValidationError;
