"""add suppliers table

Revision ID: b94918ff8152
Revises: l7a8b9c0d1e2
Create Date: 2026-05-13 21:47:40.766767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b94918ff8152'
down_revision: Union[str, None] = 'l7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_customer_outcomes_customer_id', table_name='customer_outcomes')
    op.drop_constraint('customer_outcomes_customer_id_fkey', 'customer_outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'customer_outcomes', 'customers', ['customer_id'], ['id'])
    op.add_column('purchases', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('purchases', 'supplier_name')
    op.drop_index('ix_quantity_discount_rules_user_id', table_name='quantity_discount_rules')
    op.drop_index('ix_sale_price_change_logs_sale_id', table_name='sale_price_change_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sale_price_change_logs_sale_id', 'sale_price_change_logs', ['sale_id'], unique=False)
    op.create_index('ix_quantity_discount_rules_user_id', 'quantity_discount_rules', ['user_id'], unique=False)
    op.add_column('purchases', sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'supplier_id')
    op.drop_constraint(None, 'customer_outcomes', type_='foreignkey')
    op.create_foreign_key('customer_outcomes_customer_id_fkey', 'customer_outcomes', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_customer_outcomes_customer_id', 'customer_outcomes', ['customer_id'], unique=False)
    op.drop_table('suppliers')
    # ### end Alembic commands ###
