"""add created_at to items

Revision ID: e0913a34e833
Revises: i4d5e6f7a8b9
Create Date: 2026-04-29 09:41:20.545710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e0913a34e833'
down_revision: Union[str, None] = 'i4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashbox_sessions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_cashbox_sessions_status', table_name='cashbox_sessions')
    op.drop_index('ix_cashbox_sessions_user_id', table_name='cashbox_sessions')
    op.drop_constraint('cashbox_sessions_user_id_fkey', 'cashbox_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'cashbox_sessions', 'user', ['user_id'], ['id'])
    op.alter_column('cashbox_transactions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_cashbox_transactions_session_id', table_name='cashbox_transactions')
    op.drop_index('ix_cashbox_transactions_type', table_name='cashbox_transactions')
    op.drop_index('ix_cashbox_transactions_user_id', table_name='cashbox_transactions')
    op.drop_constraint('cashbox_transactions_user_id_fkey', 'cashbox_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'cashbox_transactions', 'user', ['user_id'], ['id'])
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.drop_index('ix_customer_payments_customer_id', table_name='customer_payments')
    op.drop_constraint('customer_payments_customer_id_fkey', 'customer_payments', type_='foreignkey')
    op.create_foreign_key(None, 'customer_payments', 'customers', ['customer_id'], ['id'])
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index('ix_customers_user_id', table_name='customers')
    op.drop_constraint('customers_user_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'user', ['user_id'], ['id'])
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('purchase_items_item_id_fkey', 'purchase_items', type_='foreignkey')
    op.drop_constraint('purchase_items_purchase_id_fkey', 'purchase_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_items', 'purchases', ['purchase_id'], ['id'])
    op.create_foreign_key(None, 'purchase_items', 'items', ['item_id'], ['id'])
    op.alter_column('sale_items', 'unit_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('unit', 'gram', 'liter', 'pack', name='unittype'),
               existing_nullable=False,
               postgresql_using='unit_type::unittype')
    op.drop_index('ix_sales_customer_id', table_name='sales')
    op.drop_constraint('sales_customer_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_customer_id_fkey', 'sales', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_sales_customer_id', 'sales', ['customer_id'], unique=False)
    op.alter_column('sale_items', 'unit_type',
               existing_type=sa.Enum('unit', 'gram', 'liter', 'pack', name='unittype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.create_foreign_key('purchase_items_purchase_id_fkey', 'purchase_items', 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('purchase_items_item_id_fkey', 'purchase_items', 'items', ['item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'created_at')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_user_id_fkey', 'customers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_customers_user_id', 'customers', ['user_id'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['user_id', 'name'], unique=False)
    op.drop_constraint(None, 'customer_payments', type_='foreignkey')
    op.create_foreign_key('customer_payments_customer_id_fkey', 'customer_payments', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_customer_payments_customer_id', 'customer_payments', ['customer_id'], unique=False)
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.drop_constraint(None, 'cashbox_transactions', type_='foreignkey')
    op.create_foreign_key('cashbox_transactions_user_id_fkey', 'cashbox_transactions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cashbox_transactions_user_id', 'cashbox_transactions', ['user_id'], unique=False)
    op.create_index('ix_cashbox_transactions_type', 'cashbox_transactions', ['type'], unique=False)
    op.create_index('ix_cashbox_transactions_session_id', 'cashbox_transactions', ['session_id'], unique=False)
    op.alter_column('cashbox_transactions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'cashbox_sessions', type_='foreignkey')
    op.create_foreign_key('cashbox_sessions_user_id_fkey', 'cashbox_sessions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cashbox_sessions_user_id', 'cashbox_sessions', ['user_id'], unique=False)
    op.create_index('ix_cashbox_sessions_status', 'cashbox_sessions', ['status'], unique=False)
    op.alter_column('cashbox_sessions', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
